import { useAppStore } from '../store/use-app-store';

const translations = {
  en: {
    'loading.tagline': 'Curating safe journeys…',
    'home.nightBriefing': 'Night safety briefing',
    'home.commandCenter': 'Command center',
    'home.commandCenter.sub': 'Jump into what you need right now',
    'home.sosControl': 'SOS control',
    'home.sosControl.sub': 'Hold to dispatch concierge + emergency stack',
    'home.heatMap': 'City risk heat-map',
    'home.heatMap.sub': 'Tap filters to see theft vs harassment pockets',
    'home.focusCheckIn': 'Focus & check-in',
    'home.focusCheckIn.sub': 'Tell the app how to behave tonight',
    'home.guardianAutomations': 'Guardian automations',
    'home.guardianAutomations.sub': 'Sensors running quietly in the background',
    'home.proximityGuardians': 'Proximity guardians',
    'home.proximityGuardians.sub': 'Friends + concierge watching your route',
    'home.safeRide': 'Safe ride verification',
    'home.safeRide.sub': 'Match your driver + OTP before boarding',
    'home.timeline': 'My day timeline',
    'home.timeline.sub': 'Plans blended with local intel',
    'home.liveBoard': 'Live situation board',
    'home.liveAlerts': 'Live alerts',
    'home.localIntel': 'Local intel',
    'home.visitSuggestions': 'Visit suggestions',
    'home.visitSuggestions.sub': 'Curated spots for your current city',
    'home.trustedContacts': 'Trusted contacts',
    'home.preparedness': 'Preparedness',
    'home.hotlines': 'Hotlines',
    'profile.identity': 'Identity & badges',
    'profile.itinerary': 'Upcoming itinerary',
    'profile.documents': 'Travel documents',
    'profile.suggestions': 'Nearby suggestions',
    'profile.personalDetails': 'Personal details',
    'profile.emergencyDetails': 'Emergency & medical',
    'profile.travelPreferences': 'Travel preferences',
    'profile.badges': 'Safety streak',
    'settings.display': 'Display',
    'settings.language': 'Language',
    'settings.darkMode': 'Dark mode',
    'settings.multiLanguageLabel': 'Choose the language you prefer',
  },
  hi: {
    'loading.tagline': 'सुरक्षित यात्राएँ तैयार हो रही हैं…',
    'home.nightBriefing': 'रात्रि सुरक्षा सारांश',
    'home.commandCenter': 'कमांड सेंटर',
    'home.commandCenter.sub': 'जिस चीज़ की ज़रूरत है तुरंत पहुंचें',
    'home.sosControl': 'एसओएस नियंत्रण',
    'home.sosControl.sub': 'कंसीयर्ज़ + आपातकालीन स्टैक शुरू करें',
    'home.heatMap': 'शहर जोखिम हीट-मैप',
    'home.heatMap.sub': 'फ़िल्टर टैप करें और चोरी/उत्पीड़न पॉकेट देखें',
    'home.focusCheckIn': 'फ़ोकस व चेक-इन',
    'home.focusCheckIn.sub': 'ऐप को बताएं कि आज रात कैसे व्यवहार करे',
    'home.guardianAutomations': 'गार्जियन ऑटोमेशन',
    'home.guardianAutomations.sub': 'पृष्ठभूमि में चल रहे सेंसर',
    'home.proximityGuardians': 'नजदीकी संरक्षक',
    'home.proximityGuardians.sub': 'दोस्त + कंसीयर्ज़ रूट देख रहे हैं',
    'home.safeRide': 'सुरक्षित सवारी सत्यापन',
    'home.safeRide.sub': 'चढ़ने से पहले ड्राइवर + ओटीपी मिलाएं',
    'home.timeline': 'मेरा दिन समयरेखा',
    'home.timeline.sub': 'योजनाएँ + स्थानीय जानकारी',
    'home.liveBoard': 'लाइव स्थिति बोर्ड',
    'home.liveAlerts': 'लाइव अलर्ट',
    'home.localIntel': 'स्थानीय जानकारी',
    'home.visitSuggestions': 'भ्रमण सुझाव',
    'home.visitSuggestions.sub': 'आपके शहर के लिए चुने गए स्थान',
    'home.trustedContacts': 'विश्वसनीय संपर्क',
    'home.preparedness': 'तैयारी',
    'home.hotlines': 'हॉटलाइन',
    'profile.identity': 'पहचान व बैज',
    'profile.itinerary': 'आगामी यात्रा कार्यक्रम',
    'profile.documents': 'यात्रा दस्तावेज़',
    'profile.suggestions': 'नज़दीकी सुझाव',
    'profile.personalDetails': 'व्यक्तिगत विवरण',
    'profile.emergencyDetails': 'आपातकाल व चिकित्सा',
    'profile.travelPreferences': 'यात्रा पसंद',
    'profile.badges': 'सुरक्षा स्ट्रीक',
    'settings.display': 'डिस्प्ले',
    'settings.language': 'भाषा',
    'settings.darkMode': 'डार्क मोड',
    'settings.multiLanguageLabel': 'अपनी पसंद की भाषा चुनें',
  },
  es: {
    'loading.tagline': 'Diseñando viajes seguros…',
    'home.nightBriefing': 'Informe nocturno de seguridad',
    'home.commandCenter': 'Centro de mando',
    'home.commandCenter.sub': 'Accede al módulo que necesitas ahora',
    'home.sosControl': 'Control SOS',
    'home.sosControl.sub': 'Mantén para activar conserje + emergencia',
    'home.heatMap': 'Mapa de calor urbano',
    'home.heatMap.sub': 'Filtra zonas de robo vs acoso',
    'home.focusCheckIn': 'Modo & check-in',
    'home.focusCheckIn.sub': 'Indica cómo debe actuar la app esta noche',
    'home.guardianAutomations': 'Automatizaciones guardián',
    'home.guardianAutomations.sub': 'Sensores que vigilan en silencio',
    'home.proximityGuardians': 'Guardianes cercanos',
    'home.proximityGuardians.sub': 'Amigos + conserje vigilando tu ruta',
    'home.safeRide': 'Verificación de viaje seguro',
    'home.safeRide.sub': 'Confirma conductor + OTP antes de subir',
    'home.timeline': 'Cronograma del día',
    'home.timeline.sub': 'Plan con inteligencia local',
    'home.liveBoard': 'Tablero en vivo',
    'home.liveAlerts': 'Alertas en vivo',
    'home.localIntel': 'Inteligencia local',
    'home.visitSuggestions': 'Sugerencias para visitar',
    'home.visitSuggestions.sub': 'Lugares curados para tu ciudad',
    'home.trustedContacts': 'Contactos de confianza',
    'home.preparedness': 'Preparación',
    'home.hotlines': 'Líneas directas',
    'profile.identity': 'Identidad y distintivos',
    'profile.itinerary': 'Itinerario próximo',
    'profile.documents': 'Documentos de viaje',
    'profile.suggestions': 'Sugerencias cercanas',
    'profile.personalDetails': 'Detalles personales',
    'profile.emergencyDetails': 'Emergencia y salud',
    'profile.travelPreferences': 'Preferencias de viaje',
    'profile.badges': 'Racha de seguridad',
    'settings.display': 'Pantalla',
    'settings.language': 'Idioma',
    'settings.darkMode': 'Modo oscuro',
    'settings.multiLanguageLabel': 'Elige tu idioma preferido',
  },
  fr: {
    'loading.tagline': 'Nous sécurisons votre voyage…',
    'home.nightBriefing': 'Briefing sécurité de nuit',
    'home.commandCenter': 'Centre de commande',
    'home.commandCenter.sub': 'Accédez aussitôt à ce dont vous avez besoin',
    'home.sosControl': 'Contrôle SOS',
    'home.sosControl.sub': 'Maintenez pour alerter concierge + secours',
    'home.heatMap': 'Carte thermique des risques',
    'home.heatMap.sub': 'Filtrez vols, harcèlement ou danger',
    'home.focusCheckIn': 'Mode & check-in',
    'home.focusCheckIn.sub': 'Dites à l’app quoi faire ce soir',
    'home.guardianAutomations': 'Automatisations gardien',
    'home.guardianAutomations.sub': 'Capteurs qui tournent discrètement',
    'home.proximityGuardians': 'Gardiens proches',
    'home.proximityGuardians.sub': 'Amis + concierge surveillent votre trajet',
    'home.safeRide': 'Vérification de trajet sûr',
    'home.safeRide.sub': 'Confirmez chauffeur + OTP avant de monter',
    'home.timeline': 'Timeline de la journée',
    'home.timeline.sub': 'Plans enrichis d’intel locale',
    'home.liveBoard': 'Tableau de situation',
    'home.liveAlerts': 'Alertes en direct',
    'home.localIntel': 'Infos locales',
    'home.visitSuggestions': 'Suggestions de visite',
    'home.visitSuggestions.sub': 'Lieux recommandés autour de vous',
    'home.trustedContacts': 'Contacts de confiance',
    'home.preparedness': 'Préparation',
    'home.hotlines': 'Numéros essentiels',
    'profile.identity': 'Identité et badges',
    'profile.itinerary': 'Itinéraire à venir',
    'profile.documents': 'Documents de voyage',
    'profile.suggestions': 'Suggestions proches',
    'profile.personalDetails': 'Détails personnels',
    'profile.emergencyDetails': 'Urgence & santé',
    'profile.travelPreferences': 'Préférences de voyage',
    'profile.badges': 'Série sécurité',
    'settings.display': 'Affichage',
    'settings.language': 'Langue',
    'settings.darkMode': 'Mode sombre',
    'settings.multiLanguageLabel': 'Choisissez votre langue préférée',
  },
  ar: {
    'loading.tagline': 'نجهز رحلتك الآمنة…',
    'home.nightBriefing': 'موجز السلامة الليلي',
    'home.commandCenter': 'مركز التحكم',
    'home.commandCenter.sub': 'انتقل بسرعة إلى ما تحتاجه الآن',
    'home.sosControl': 'زر الطوارئ SOS',
    'home.sosControl.sub': 'اضغط مطولاً لتنبيه الطوارئ والكونسيرج',
    'home.heatMap': 'خريطة المخاطر الحرارية',
    'home.heatMap.sub': 'اعرض مناطق السرقة أو التحرش أو الخطر',
    'home.focusCheckIn': 'وضع التركيز والتطمين',
    'home.focusCheckIn.sub': 'أخبر التطبيق كيف يتصرف هذه الليلة',
    'home.guardianAutomations': 'أتمتة الحماية',
    'home.guardianAutomations.sub': 'مجسات تعمل بهدوء في الخلفية',
    'home.proximityGuardians': 'حماة بالقرب منك',
    'home.proximityGuardians.sub': 'الأصدقاء والكونسيرج يراقبون مسارك',
    'home.safeRide': 'التحقق من الرحلة الآمنة',
    'home.safeRide.sub': 'طابق السائق ورمز OTP قبل الركوب',
    'home.timeline': 'مخطط يومي',
    'home.timeline.sub': 'خطة مدمجة مع معلومات محلية',
    'home.liveBoard': 'لوحة الحالة المباشرة',
    'home.liveAlerts': 'تنبيهات مباشرة',
    'home.localIntel': 'معلومات محلية',
    'home.visitSuggestions': 'اقتراحات للزيارة',
    'home.visitSuggestions.sub': 'أماكن مختارة لمدينتك الحالية',
    'home.trustedContacts': 'جهات موثوقة',
    'home.preparedness': 'الجاهزية',
    'home.hotlines': 'أرقام الطوارئ',
    'profile.identity': 'الهوية والشارات',
    'profile.itinerary': 'الرحلة القادمة',
    'profile.documents': 'وثائق السفر',
    'profile.suggestions': 'اقتراحات قريبة',
    'profile.personalDetails': 'تفاصيل شخصية',
    'profile.emergencyDetails': 'الطوارئ والصحة',
    'profile.travelPreferences': 'تفضيلات السفر',
    'profile.badges': 'سجل السلامة',
    'settings.display': 'العرض',
    'settings.language': 'اللغة',
    'settings.darkMode': 'الوضع الداكن',
    'settings.multiLanguageLabel': 'اختر لغتك المفضلة',
  },
};

type TranslationKey = keyof typeof translations.en;

export const useTranslate = () => {
  const language = useAppStore((state) => state.language);

  return (key: TranslationKey): string => {
    const locale = translations[language] || translations.en;
    return locale[key] || translations.en[key] || key;
  };
};

export const SUPPORTED_LANGUAGES = [
  { id: 'en', label: 'English' },
  { id: 'hi', label: 'हिंदी' },
  { id: 'es', label: 'Español' },
  { id: 'fr', label: 'Français' },
  { id: 'ar', label: 'العربية' },
] as const;
